defaults:
  - datamodule: cape
  - deformer: fast_snarf

hydra:
  run:
    dir: outputs/${expname}/${subject}

expname: cape
subject: 3375
epoch: last
resume: false

trainer:
  gradient_clip_val: 0
  check_val_every_n_epoch: 5
  deterministic: false
  max_steps: 45000
  gpus: 1
model:
  # shape MLP
  softmax: true
  network:
    multires: 4
    cond_layer: [0]
    dim_cond_embed: -1
    d_in: 3
    d_out: 1
    depth: 8
    width: 256
    skip_layer: [4]
    weight_norm: true
    geometric_init: true
    bias: 1
    use_tanh: false
  optim:
    lr: 1e-3
  soft_blend: 5
  nepochs_pretrain: 1
  nepochs_tv: 200
  lambda_bone_occ: 1
  lambda_bone_w: 10
  lambda_tv: 1

  deformer:
    _target_: lib.model.fast_snarf.ForwardDeformer
    opt:
      align_corners: true
      skinning_mode: mlp
      res: 64
      z_ratio: 4
      softmax_mode: softmax
      global_scale: 1.2
      soft_blend: 20
      cvg: 1e-4
      dvg: 5e-1
      network:
        d_in: 3
        d_out: 24
        depth: 4
        width: 128
        multires: 0
        skip_layer: []
        cond_layer: []
        dim_cond_embed: 0
        weight_norm: true
        geometric_init: false
        bias: 1

demo:
  motion_path: data/aist_demo/seqs
  resolution: 256
  save_mesh: false
  every_n_frames: 2
  output_video_name: aist
  verbose: false
  fast_mode: false